#!/usr/bin/env ruby

require File.expand_path('../lib/alchemy', __FILE__)
require 'benchmark'

Slop.parse :help => true do
  banner "./generate [options]\n"

  on 'foo', 'fancy testing method' do
    # Turn string into seed
    seed = "Pastel"
#    seed = "Sally"
#    seed = "Ashley"
    seed = "Tiffy"
    ap [seed, seed.to_seed]
#    seed = nil
    options = {
      :seed => seed.to_seed,
      :dpi => 200,
      :circle_type => :random_polygons_circle
    }
    circ = Alchemy.generate_alchemy_circle options
    circ = circ.draw
    circ.format = 'png'
    ap circ.to_blob
#    circ.draw.write('/home/brandon/web/test.png') if circ != nil
  end

  on 'O', 'open-irb-session', 'Open an IRB session with everything loaded' do
    system('irb -I lib -ralchemy')
  end

end
